apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  mysql-host: mysql-service
  database-name: "studentsdb"
  nginx.conf: |
    server {
      listen 80;
      listen [::]:80;
      access_log off;
      root /var/www/html;
      index index.php;
      server_name example.com;
      server_tokens off;
      location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri/ /index.php?$args;
      }
      # pass the PHP scripts to FastCGI server listening on wordpress:9000
      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
          
        # Change The Service Name
        fastcgi_pass phpfpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
      }
    }
  initdb.sql: |
    use studentsdb;
    CREATE TABLE Students (rollnum varchar(255),firstname varchar(255),lastname varchar(255));
    INSERT INTO Students (rollnum, firstname, lastname) VALUES ("19B-080-SE", "Abdul", "Wassay");
    INSERT INTO Students (rollnum, firstname, lastname) VALUES ("19B-115-SE", "Sheikh", "Birjees Ali");